### ISSUE TITLE
Unable to fetch the package

### ISSUE THREAD

**Issue by ph55** [mgechev/is-esm#1]
"Unable to fetch the package" error thrown when used:

![image](https://user-images.githubusercontent.com/1386622/112544812-2477cb80-8dc0-11eb-9832-5929dd6569f1.png)
![image](https://user-images.githubusercontent.com/1386622/112544638-eda1b580-8dbf-11eb-92b2-dfca14c693aa.png)

node -v: v14.14.0
npm -v: 7.6.3

**Comment by mgechev** [comment]
Can't reproduce. Any details about your network?
