### ISSUE TITLE
False-negative when using npm v7

### ISSUE THREAD

**Issue by amikheychik** [mgechev/is-esm#2]
It looks like at the moment, npm v7 returns "No" in any case.

This is an test run, first on node 12 / npm 6; then node 12 / npm 7, and then back on node 12 / npm 6:

```
➜  nvm use 12.20.0
Now using node v12.20.0 (npm v6.14.13)
➜  npx is-esm @angular/core
npx: installed 58 in 2.737s
✔ Yes


➜  npm install -g npm@7
…
+ npm@7.18.1
added 62 packages from 25 contributors, removed 242 packages and updated 193 packages in 4.412s
➜  nvm use 12.20.0
Now using node v12.20.0 (npm v7.18.1)
➜  npx is-esm @angular/core
⚠ No


➜  npm install -g npm@6

removed 62 packages, changed 99 packages, and audited 436 packages in 2s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
➜  nvm use 12
Now using node v12.20.0 (npm v6.14.13)
➜  npx is-esm @angular/core
npx: installed 58 in 2.618s
✔ Yes
```

I tried to debug it, but so far found that running `installCommand` doesn't not create `node_modules` in the temporary directory.

With `npm@6` the `stdout` of `installModules()` is:

```
added 2 packages from 2 contributors and audited 2 packages in 0.866s
found 0 vulnerabilities
```

But `npm@7` it is:

```
up to date, audited 7 packages in 925ms

found 0 vulnerabilities
```

I think it's related to the `--prefix`, as running the same command in the temp dir without it works fine.

**Comment by amikheychik** [comment]
Probably is caused by this: https://github.com/npm/cli/issues/3256

**Comment by mgechev** [comment]
I couldn't reproduce with `7.20.3`. Could you double check with the latest version and let me know if the issue is still relevant?

**Comment by amikheychik** [comment]
Sure, I'm a bit overwhelmed with things at the moment, but will try to get to it in the next couple weeks.

**Comment by amikheychik** [comment]
Sorry for the delay with the response. I've confirmed it is working fine now (npm `7.22.0`):

```
➜  npm install -g npm@7
...
+ npm@7.22.0
added 70 packages from 27 contributors, removed 248 packages and updated 187 packages in 4.432s
➜  nvm use 12.20.0
Now using node v12.20.0 (npm v7.22.0)
➜  npx is-esm @angular/core
✔ Yes
```
